padding-x = 10
padding-y = [10, 10]
option-as-alt = 'left'
confirm-before-quit = false

[editor]
program = "code"

[window]
width = 600
height = 400
mode = "Windowed"
blur = false
decorations = "enabled"

[fonts]
size = 20
family = "Calex Code JP"
weight = 800

[colors]
background = '#1F2428'
foreground = '#D1D5DA'
selection-background = '#3b5070'
# selection-foreground = '#ffffff'
cursor = '#79B8FF'
black = '#000000'
red = '#F97583'
green = '#56d364'
yellow = '#e3b341'
blue = '#6ca4f8'
magenta = '#db61a2'
cyan = '#2b7489'
white = '#ffffff'
light_black = '#4d4d4d'
light_red = '#f78166'
light_green = '#56d364'
light_yellow = '#e3b341'
light_blue = '#6ca4f8'
light_magenta = '#db61a2'
light_cyan = '#2b7489'
light_white = '#ffffff'