version: "3"

tasks:
  default:
    desc: "Show task list"
    cmds:
      - task --list

  open:dotfiles:
    desc: "Open dotfiles in editor"
    cmds:
      - code ~/dotfiles

  apply:
    desc: "Apply Nix configuration"
    silent: true
    vars:
      HOSTNAME:
        sh: hostname -s
      FIRST_ARG: "{{if .CLI_ARGS}}{{index .CLI_ARGS 0}}{{else}}{{end}}"
    cmds:
      - |
        TARGET="{{.FIRST_ARG}}"
        TARGET="${TARGET:-{{.HOSTNAME}}}"

        DIR="$HOME/dotfiles/system/$TARGET"

        if [ ! -d "$DIR" ]; then
          echo "Error: System config for \"$TARGET\" not found at $DIR"
          exit 1
        fi

        if [ -n "{{.FIRST_ARG}}" ]; then
          shift
        fi

        exec "$DIR/apply.sh" "$@" {{.ARGS}}

  apply:update:
    desc: "Update flake.lock and apply"
    silent: true
    cmds:
      - task: apply
        vars: { ARGS: "--update {{.CLI_ARGS}}" }

  dev:init:
    desc: "Initialize devbox & direnv"
    dir: "{{.USER_WORKING_DIR}}"
    silent: true
    cmds:
      - devbox init
      - devbox generate direnv -q
